In [16]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn import preprocessing
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import make_classification
from sklearn import tree
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
import matplotlib.pyplot as plt
import math

df=pd.read_csv('dermatology_csv.csv')
#x=df.iloc[:,0:34]
#y=df.iloc[:,34]
df.head()



erythema  scaling  definite_borders  itching  koebner_phenomenon  \
0         2        2                 0        3                   0   
1         3        3                 3        2                   1   
2         2        1                 2        3                   1   
3         2        2                 2        0                   0   
4         2        3                 2        2                   2   

   polygonal_papules  follicular_papules  oral_mucosal_involvement  \
0                  0                   0                         0   
1                  0                   0                         0   
2                  3                   0                         3   
3                  0                   0                         0   
4                  2                   0                         2   

   knee_and_elbow_involvement  scalp_involvement  ...  \
0                           1                  0  ...   
1                           1                  1  ...   
2                           0                  0  ...   
3                           3                  2  ...   
4                           0                  0  ...   

   disappearance_of_the_granular_layer  \
0                                    0   
1                                    0   
2                                    0   
3                                    3   
4                                    2   

   vacuolisation_and_damage_of_basal_layer  spongiosis  \
0                                        0           3   
1                                        0           0   
2                                        2           3   
3                                        0           0   
4                                        3           2   

   saw-tooth_appearance_of_retes  follicular_horn_plug  \
0                              0                     0   
1                              0                     0   
2                              2                     0   
3                              0                     0   
4                              3                     0   

   perifollicular_parakeratosis  inflammatory_monoluclear_inflitrate  \
0                             0                                    1   
1                             0                                    1   
2                             0                                    2   
3                             0                                    3   
4                             0                                    2   

   band-like_infiltrate   age  class  
0                     0  55.0      2  
1                     0   8.0      1  
2                     3  26.0      3  
3                     0  40.0      1  
4                     3  45.0      3  

[5 rows x 35 columns]

In [17]:
#logistic regression

#handling missing values
array=df.values
X=array[:,0:34]
y=array[:,34]
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer
imp = IterativeImputer(max_iter=10, random_state=0)
imp.fit(X)
X=np.round(imp.transform(X))

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2)

#normalize the feature
scaler = StandardScaler()
X_train=scaler.fit_transform(X_train)

X_test=scaler.fit_transform(X_test)

accuracy=[]
names=[]


logistic_regression=LogisticRegression(solver='lbfgs',multi_class='multinomial',max_iter=1000)

logistic_regression.fit(X_train,y_train)
logistic_regression_predict=logistic_regression.predict(X_test)
# logistic_acc=logistic_regression.score(X,y)
# print('accuracy of logistic regression : {:.3f}%\n'.format(logistic_acc*100))

print('classification Report :\n',classification_report(y_test,logistic_regression_predict))

confusion=confusion_matrix(y_test,logistic_regression_predict)
print(confusion)


classification Report :
               precision    recall  f1-score   support

         1.0       1.00      0.96      0.98        27
         2.0       0.88      0.88      0.88         8
         3.0       1.00      1.00      1.00        11
         4.0       0.89      1.00      0.94         8
         5.0       1.00      1.00      1.00        17
         6.0       1.00      1.00      1.00         3

    accuracy                           0.97        74
   macro avg       0.96      0.97      0.97        74
weighted avg       0.97      0.97      0.97        74

[[26  1  0  0  0  0]
 [ 0  7  0  1  0  0]
 [ 0  0 11  0  0  0]
 [ 0  0  0  8  0  0]
 [ 0  0  0  0 17  0]
 [ 0  0  0  0  0  3]]


In [18]:
#Decision tree

#handling missing values
array=df.values
X=array[:,0:34]
y=array[:,34]
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer
imp = IterativeImputer(max_iter=10, random_state=0)
imp.fit(X)
X=np.round(imp.transform(X))

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2)

decision_tree=DecisionTreeClassifier(criterion='gini')

decision_tree.fit(X_train,y_train)
decision_tree_predict=decision_tree.predict(X_test)
#decision_acc=decision_tree.score(x,y)


print('classification Report :\n',classification_report(y_test,decision_tree_predict))

confusion=confusion_matrix(y_test,decision_tree_predict)
print(confusion)


names.append('Decision tree')
#accuracy.append(decision_acc)

classification Report :
               precision    recall  f1-score   support

         1.0       1.00      1.00      1.00        21
         2.0       0.88      1.00      0.93         7
         3.0       1.00      0.94      0.97        16
         4.0       1.00      0.92      0.96        13
         5.0       0.91      1.00      0.95        10
         6.0       1.00      1.00      1.00         7

    accuracy                           0.97        74
   macro avg       0.96      0.98      0.97        74
weighted avg       0.98      0.97      0.97        74

[[21  0  0  0  0  0]
 [ 0  7  0  0  0  0]
 [ 0  0 15  0  1  0]
 [ 0  1  0 12  0  0]
 [ 0  0  0  0 10  0]
 [ 0  0  0  0  0  7]]


In [19]:
#Support Vector Machine
#handling missing values
array=df.values
X=array[:,0:34]
y=array[:,34]
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer
imp = IterativeImputer(max_iter=10, random_state=0)
imp.fit(X)
X=np.round(imp.transform(X))

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.1)

#normalize the feature
scaler = StandardScaler()
X_train=scaler.fit_transform(X_train)

X_test=scaler.fit_transform(X_test)

accuracy=[]
names=[]


svm=SVC( kernel='linear',max_iter=-1)

svm.fit(X_train,y_train)
svm_predict=svm.predict(X_test)

#svm_accuracy=svm.score(x,y)



print('classification Report :\n',classification_report(y_test,svm_predict))

confusion=confusion_matrix(y_test,svm_predict)
print(confusion)


#accuracy.append(decision_acc)

classification Report :
               precision    recall  f1-score   support

         1.0       1.00      1.00      1.00         9
         2.0       1.00      0.92      0.96        13
         3.0       1.00      1.00      1.00         5
         4.0       0.80      1.00      0.89         4
         5.0       1.00      1.00      1.00         5
         6.0       1.00      1.00      1.00         1

    accuracy                           0.97        37
   macro avg       0.97      0.99      0.97        37
weighted avg       0.98      0.97      0.97        37

[[ 9  0  0  0  0  0]
 [ 0 12  0  1  0  0]
 [ 0  0  5  0  0  0]
 [ 0  0  0  4  0  0]
 [ 0  0  0  0  5  0]
 [ 0  0  0  0  0  1]]


In [20]:
#Random Forest
#handling missing values
array=df.values
X=array[:,0:34]
y=array[:,34]
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer
imp = IterativeImputer(max_iter=10, random_state=0)
imp.fit(X)
X=np.round(imp.transform(X))

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.1)




random_forest=RandomForestClassifier(criterion='gini',)

random_forest.fit(X_train,y_train)
random_forest_predict=random_forest.predict(X_test)
#random_forest_accuracy=random_forest.score(x,y)

#print('accuracy of Decision tree : {:.3f}%\n'.format(random_forest_accuracy*100))

print('classification Report :\n',classification_report(y_test,random_forest_predict))

confusion=confusion_matrix(y_test,random_forest_predict)
print(confusion)

classification Report :
               precision    recall  f1-score   support

         1.0       1.00      1.00      1.00        17
         2.0       1.00      1.00      1.00         6
         3.0       1.00      1.00      1.00         7
         4.0       1.00      1.00      1.00         1
         5.0       1.00      1.00      1.00         3
         6.0       1.00      1.00      1.00         3

    accuracy                           1.00        37
   macro avg       1.00      1.00      1.00        37
weighted avg       1.00      1.00      1.00        37

[[17  0  0  0  0  0]
 [ 0  6  0  0  0  0]
 [ 0  0  7  0  0  0]
 [ 0  0  0  1  0  0]
 [ 0  0  0  0  3  0]
 [ 0  0  0  0  0  3]]
